# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b839183ab3d31b2ed9d51aa969447c24819f94282beda35cc9d6dedd55fadbcd14a8945512cb6633940c1a458d356a3a51d9dd9584d0cafb22ff92c1dd8ddbee

test:
  secret_key_base: 356a579346d4f8e8ecfb5bf5aad3db47144eae61bd0cffa53f6498f4f05aea199d8afd17d8f190648505a2a9a8e0711e5a738072507a6028c2b4adc0005000fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
